import { StyleSheet, Dimensions } from "react-native";
import { COLORS, SPACING, TYPOGRAPHY, SHADOWS } from "../../constants/theme";

const { width } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    minHeight: "100%",
    width: "100%",
    flexDirection: "column",
    backgroundColor: COLORS.white,
  },
  hero: {
    position: "relative",
    height: 380, 
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
  },
  heroBg: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
  },
  heroOverlay: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
  },
  heroContent: {
    position: "relative",
    zIndex: 10,
    paddingHorizontal: SPACING.xl, 
    maxWidth: 600,
  },
  navbar: {
    backgroundColor: COLORS.white,  
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  navLogo: {
    width: 100,
    height: 55,
  },
  heroTitle: {
    fontSize: 32, 
    fontWeight: TYPOGRAPHY.weights.extrabold,
    lineHeight: 38,
    marginBottom: SPACING.md,
    color: COLORS.white,
  },
  heroHighlight: {
    color: COLORS.accent,
  },
  heroSubtitle: {
    fontSize: TYPOGRAPHY.sizes.sm,
    marginBottom: SPACING.lg,
    lineHeight: 22,
    opacity: 0.9,
    color: COLORS.white,
  },
  heroButtons: {
    flexDirection: "row",
    gap: 16,
    flexWrap: "wrap",
  },
  heroBtnPrimary: {
    backgroundColor: COLORS.accent,
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 32,
    ...SHADOWS.sm,
  },
  heroBtnOutline: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: COLORS.accent,
    paddingVertical: 10,
    paddingHorizontal: 32,
    borderRadius: 32,
  },
  credentialsSection: {
    paddingHorizontal: SPACING.lg, 
    paddingTop: 48, 
    paddingBottom: 48,
    backgroundColor: COLORS.white,
  },
  sectionTitle: {
    fontSize: 28, 
    fontWeight: TYPOGRAPHY.weights.extrabold,
    color: COLORS.primary,
    marginBottom: 48,
  },
  credentialsGrid: {
    flexDirection: "column", 
    gap: 40, 
  },
  credentialCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    overflow: "hidden",
    flexDirection: "column",
    backgroundColor: COLORS.white,
    width: "100%", 
    padding: 0,
    ...SHADOWS.sm,
  },
  cardHeaderBg: {
    height: 120, 
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  headerColor1: { backgroundColor: "#BFDBFE" },
  headerColor2: { backgroundColor: "#FED7AA" },
  headerColor3: { backgroundColor: "#9CA3AF" },
  headerColor4: { backgroundColor: "#FBBF24" },
  headerColor5: { backgroundColor: "#FCA5A5" },
  headerColor6: { backgroundColor: "#C4B5FD" },
  cardIconWrapper: {
    justifyContent: "center",
    alignItems: "center",
  },
  cardIcon: {
    color: COLORS.darkgray,
    opacity: 0.6,
  },
  cardContent: {
    padding: SPACING.xl, 
    flex: 1,
    flexDirection: "column",
  },
  cardTitle: {
    fontSize: TYPOGRAPHY.sizes.xl, 
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.darkgray,
    marginBottom: 8,
  },
  cardDesc: {
    fontSize: TYPOGRAPHY.sizes.sm,
    color: COLORS.textMuted,
    marginBottom: SPACING.lg,
    lineHeight: 20,
    flex: 1,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 0, 
  },
  priceTag: {
    fontWeight: TYPOGRAPHY.weights.extrabold,
    color: COLORS.primary,
    fontSize: 18, 
  },
  requestBtnSmall: {
    backgroundColor: COLORS.accent,
    borderRadius: 16,
    paddingVertical: 4,
    paddingHorizontal: 16,
    ...SHADOWS.sm,
  },
  seeMoreBtn: {
    alignSelf: "center",
    marginTop: 80,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 28,
    backgroundColor: COLORS.white,
  },
  seeMoreBtnText: {
    fontSize: TYPOGRAPHY.sizes.sm,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.primary,
  },
  statusSection: {
    paddingVertical: 48,
    paddingHorizontal: SPACING.lg,
    backgroundColor: COLORS.primary,
    alignItems: "center",
  },
  statusCard: {
    backgroundColor: "transparent", 
    padding: 0, 
    elevation: 0,
    shadowColor: "transparent",
    alignItems: "center", 
    width: "100%",
  },
  statusTitle: {
    fontSize: 32, 
    fontWeight: TYPOGRAPHY.weights.extrabold,
    marginBottom: SPACING.md,
    color: COLORS.white,
    textAlign: "center",
  },
  statusSubtitle:{
    fontSize: TYPOGRAPHY.sizes.md, 
    opacity: 0.9,
    textAlign: "center",
    marginBottom: SPACING.xl,
    color: COLORS.white,
  },
  statusCheckContainer: {
    width: "100%",
    maxWidth: 600,
    backgroundColor: COLORS.white,
    padding: SPACING.md, 
    borderRadius: 12,
    flexDirection: "column", 
    gap: 8,
  },
  statusInput: {
    flex: 1,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.darkgray,
    borderWidth: 0,          
  },
  statusBtn: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    justifyContent: "center",
    borderRadius: 8,
  },
  featuresSection: {
    paddingVertical: 48,
    paddingHorizontal: SPACING.lg,
    backgroundColor: COLORS.white,
  }
});